### ISSUE TITLE
Disable ability to submit unedit placeholder

### ISSUE THREAD

**Issue by martijnsublime** [datacamp/RDocumentation-app#271] opened 2016-10-15 13:00 UTC
See: https://www.dropbox.com/s/xlgqe4fikyv5ltv/Screenshot%202016-10-15%2008.58.25.png?dl=0

**Comment by ludov04** [comment] 2016-10-17 08:33
duplicate of https://github.com/datacamp/RDocumentation-app/issues/262
I'm going to reprioritize this, seems like lot of people does it

**Closed** 2016-10-17 08:34 UTC
Labels: duplicate
