### ISSUE TITLE
rdocumentation.org is not showing new packages(anymore) - stopped Thu Nov 02

### ISSUE THREAD

**Issue by AndreMikulec** [datacamp/RDocumentation-app#390] opened 2017-11-05 14:45 UTC
Today is Sun Nov 05.

When I browse to the URL
https://www.rdocumentation.org/trends
I only see

```
Newest packages 
readobj           Thu Nov 02 2017 19:10:13
equateMultiple    Thu Nov 02 2017 18:12:55
politeness        Thu Nov 02 2017 15:39:37
```

**Comment by filipsch** [comment] 2018-01-05 19:00
Duplicate of #394

**Closed by filipsch** 2018-01-05 19:00 UTC
