### ISSUE TITLE
rdocumentation.org is not showing new packages(anymore) - stopped Wed Oct 25 2017

### ISSUE THREAD

**Issue by AndreMikulec** [datacamp/RDocumentation-app#388] opened 2017-10-30 12:12 UTC
Today is Mon Oct 30

When I browse to the URL
https://www.rdocumentation.org/trends
I only see

### Newest packages 

```
actogrammr  Wed Oct 25 2017 17:24:10
MEPDF       Wed Oct 25 2017 10:22:07
hdf5r       Wed Oct 25 2017 09:45:44
```

**Comment by filipsch** [comment] 2018-01-05 19:00
Duplicate of #394

**Closed by filipsch** 2018-01-05 19:00 UTC
