### ISSUE TITLE
Bad Parsing of tm::TextDocument

### ISSUE THREAD

**Issue by richierocks** [datacamp/RDocumentation-app#367] opened 2017-07-13 09:00 UTC
The problem occurs in an older version of the help page.

https://www.rdocumentation.org/packages/tm/versions/0.5-10/topics/TextDocument

I see

![screenshot 2017-07-13 09 50 31](https://user-images.githubusercontent.com/197589/28158162-bdd3f694-67b0-11e7-96e7-148b88361db7.png)

This doesn't occur in `0.6-2` of the page.

**Comment by ludov04** [comment] 2017-07-20 08:55
The issue is actually fixed in the new parser but old version are not being reparsed, tagging that as a duplicate of #294, as once #294 is fixed, older versions will be reparsed aswell, thanks for raising

**Closed by ludov04** 2017-07-20 08:55 UTC
